name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        install: >-
          base-devel
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-make
          mingw-w64-x86_64-pkgconf
          mingw-w64-x86_64-go
          autoconf
          automake
          libtool
          wget
          unzip
    - name: Build Yara
      shell: msys2 {0}
      run: |
        wget https://github.com/VirusTotal/yara/archive/refs/tags/v4.1.0.zip
        unzip v4.1.0.zip
        cd yara-4.1.0
        ./bootstrap.sh
        mkdir build
        cd build
        ../configure
        make -C . install
    - name: Build
      shell: mysys2 {0}
      run: GOARCH=amd64 CGO_ENABLED=1 go build -ldflags "-extldflags=-static" -tags yara_static -o tripwire.exe .
