name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        install: >-
          base-devel
          gcc
          pkg-config
          autoconf
          automake
          libtool
          wget
          unzip
    - name: Build Yara
      shell: msys2 {0}
      run: |
        wget https://github.com/VirusTotal/yara/archive/refs/tags/v4.1.0.zip
        unzip v4.1.0.zip
        cd yara-4.1.0
        ./bootstrap.sh
        mkdir build
        cd build
        ../configure
        make -C . install
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Build
      run: |
        set PATH="%PATH%;C:\msys64\mingw64\bin"
        set CGO_ENABLED=1
        set GOARCH=amd64
        go build -ldflags "-extldflags=-static" -tags yara_static -o tripwire.exe .
